version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  shorty:
    container_name: shorty
    build: .
    image: shorty
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    restart: always
